### ISSUE TITLE
Export aborts with error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openbmap/android#58]
```
What steps will reproduce the problem?
1. Log data.
2. Choose to keep uploaded files and export GPX.
3. Upload.

What is the expected output? What do you see instead?
Expected: a clean upload. Instead: Cell & wifi data is exported, then uploaded, 
finally GPX is exported and eventually I get a message that the upload failed. 
On one occasion during pload I noticed that the number of files went down one 
by one, then jumped up by ~8–10 files, then slowly went down again, then 
jumped up again. The whole cycle repeated many times until the number of files 
was at zero. On other occasions the number of files went down steadily.

What version of the product are you using? On what operating system?
0.7.9 (the Dec 27 version from Google Drive.) OS is Cyanogenmod 10.2 on Nexus S.

Please provide any additional information below.


```

Original issue reported on code.google.com by `mich...@vonglasow.com` on 23 Jan 2014 at 7:35

**Comment by iliketurtlesbro** [comment]
I too am having issues uploading. I began getting upload errors beginning Aug 3 of this year, and ever since then I have been unable to upload my collected data. I'm using radio beacon version 0.8.8 from F-Droid. Running CyanogenMod 12.1 Android 5.1.1 on Nexus 6.

**Comment by wish7code** [comment]
Thanks for reporting! Technically there've been no breaking changes server side since Aug 3.
Nevertheless we've had some high server loads in the last couple of days. So side-effects on the upload function may have happened, although I wouldn't expect such effects at first glance.

May I ask about your upload method? Did you use 2G, 3G or wifi networks? Which speed?
Cheers
Toby

**Comment by TimSC** [comment]
I'm having upload problems today. I'm using wifi.

Interesting project by the way!

**Comment by wish7code** [comment]
OK, I double checked the uploads, unfortunately the files didn't make it to the server.
On the other hand, I just tried to upload from my phone and it seems to work.

Could you share a logcat if the problems persists?

Thanks & cheers
Toby

**Comment by TimSC** [comment]
@wish7code I spotted something in logcat: Error while uploading/storage/sdcard0/Android/data/org.openbmap/filesV1_log20150824103650-wifi.xml: Server reply 401

I'll try update my account info. It might be helpful to have a friendly error message!

**Comment by wish7code** [comment]
Glad to hear! Took me a while until I realise, this was actually a 401 password issue:-)
Recently I already pushed a change to the repos which display a "Bad user name or password" instead of the generic error message. 

Still fixing some other issues and then publish everything on F-Droid...

> btw, it was not very easy finding the upload button.

Good point, following your suggestion I opened feature request #90. First idea, add a button in the top menu bar...

Cheers 
Toby

**Comment by TimSC** [comment]
Thanks, I look forward to contributing data.

**Comment by b166er** [comment]
![screenshot_2015-12-15-12-29-38](https://cloud.githubusercontent.com/assets/679114/11809762/5fefd66c-a329-11e5-9660-96042d5ce19b.png)
Hello,
i can't upload few files for a long time. after i click to upload, i got the message:
"Export error
Try again later. If problem persists, please file a bug at http://code.google.com/p/openbmap/issues/list"

i tried to upload also with current version 0.8.11 (from f-droid), but nothing helps. what is wrong with this files? and where i can upload this files or can i send them to someone? thanks.

**Comment by wish7code** [comment]
Strange enough: at least some of your uploads have made it to the server (see http://www.radiocells.org/stats/scoreboard)

Could you try the following: go to Settings --> Advanced settings and activate 'Skip uploap' and 'Keep uploaded files'. Then export a session as normal.

Following that you'll find the xml files in the openbmap folder (usually sdcard\Android\data\org.openbmap\files).

Zip them and send them to team@radioc......org and we'll take care of the upload manually.

To debug, could you provide a logcat too?

Thanks & Cheers
Toby

**Comment by b166er** [comment]
for the record: email sent with files and log. Problem solved by dev-team, thank you for the email-reply.
